// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyKl_HJdrLS-2B3KcHz1U3zcyv9o2jDSI',
    appId: '1:777621007253:web:e9a414a834d29f129c649c',
    messagingSenderId: '777621007253',
    projectId: 'zinx-firebase-master',
    authDomain: 'zinx-firebase-master.firebaseapp.com',
    storageBucket: 'zinx-firebase-master.appspot.com',
    measurementId: 'G-Q67ZBRKWQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhR2ZFhe5RNNXGoSzb1_wxf7g0WmtQRvU',
    appId: '1:777621007253:android:010444304f2f975f9c649c',
    messagingSenderId: '777621007253',
    projectId: 'zinx-firebase-master',
    storageBucket: 'zinx-firebase-master.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN1KGz8jl5R_fhHokuHpIwaeFyDQrNfpE',
    appId: '1:777621007253:ios:788452884b0041759c649c',
    messagingSenderId: '777621007253',
    projectId: 'zinx-firebase-master',
    storageBucket: 'zinx-firebase-master.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN1KGz8jl5R_fhHokuHpIwaeFyDQrNfpE',
    appId: '1:777621007253:ios:788452884b0041759c649c',
    messagingSenderId: '777621007253',
    projectId: 'zinx-firebase-master',
    storageBucket: 'zinx-firebase-master.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyKl_HJdrLS-2B3KcHz1U3zcyv9o2jDSI',
    appId: '1:777621007253:web:d51983fc29c146e99c649c',
    messagingSenderId: '777621007253',
    projectId: 'zinx-firebase-master',
    authDomain: 'zinx-firebase-master.firebaseapp.com',
    storageBucket: 'zinx-firebase-master.appspot.com',
    measurementId: 'G-LPBV5X7PC6',
  );
}
